# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ('create_time',)},
        ),
    ]
