# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20160723_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.UserMessage'),
        ),
    ]
